CREATE TABLE `company_settings` (
	`user_id` text PRIMARY KEY NOT NULL,
	`cnpj` text,
	`razao_social` text,
	`inscricao_municipal` text,
	`nome_fantasia` text,
	`street` text,
	`number` text,
	`complement` text,
	`neighborhood` text,
	`city` text,
	`state` text,
	`zip_code` text,
	`city_code` integer,
	`service_description` text,
	`cnae_code` text,
	`iss_rate` integer,
	`municipality_code` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `nfse_records` (
	`id` text PRIMARY KEY NOT NULL,
	`invoice_id` text NOT NULL,
	`user_id` text NOT NULL,
	`fiscal_nacional_id` text,
	`nfse_number` text,
	`nfse_verification_code` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`pdf_url` text,
	`pdf_r2_key` text,
	`xml_url` text,
	`xml_r2_key` text,
	`cnpj` text,
	`razao_social` text,
	`inscricao_municipal` text,
	`service_description` text,
	`cnae_code` text,
	`city_code` integer,
	`iss_amount` integer,
	`net_amount` integer,
	`error_message` text,
	`attempt_count` integer DEFAULT 0 NOT NULL,
	`emitted_at` integer,
	`cancelled_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
