/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as protectedDashboardSettingsRouteImport } from './routes/(protected)/dashboard/settings'
import { Route as protectedDashboardProfileRouteImport } from './routes/(protected)/dashboard/profile'
import { Route as protectedDashboardInvoicesRouteImport } from './routes/(protected)/dashboard/invoices'
import { Route as protectedDashboardBillingRouteImport } from './routes/(protected)/dashboard/billing'
import { Route as protectedDashboardApiKeysRouteImport } from './routes/(protected)/dashboard/api-keys'
import { Route as protectedDashboardSettingsNotificationsRouteImport } from './routes/(protected)/dashboard/settings/notifications'
import { Route as protectedDashboardSettingsCompanyRouteImport } from './routes/(protected)/dashboard/settings/company'
import { Route as protectedDashboardInvoicesIdRouteImport } from './routes/(protected)/dashboard/invoices/$id'
import { Route as protectedDashboardBillingUpgradeRouteImport } from './routes/(protected)/dashboard/billing/upgrade'
import { Route as protectedDashboardBillingHistoryRouteImport } from './routes/(protected)/dashboard/billing/history'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedDashboardSettingsRoute =
  protectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardProfileRoute =
  protectedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardInvoicesRoute =
  protectedDashboardInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardBillingRoute =
  protectedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardApiKeysRoute =
  protectedDashboardApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardSettingsNotificationsRoute =
  protectedDashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => protectedDashboardSettingsRoute,
  } as any)
const protectedDashboardSettingsCompanyRoute =
  protectedDashboardSettingsCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => protectedDashboardSettingsRoute,
  } as any)
const protectedDashboardInvoicesIdRoute =
  protectedDashboardInvoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => protectedDashboardInvoicesRoute,
  } as any)
const protectedDashboardBillingUpgradeRoute =
  protectedDashboardBillingUpgradeRouteImport.update({
    id: '/upgrade',
    path: '/upgrade',
    getParentRoute: () => protectedDashboardBillingRoute,
  } as any)
const protectedDashboardBillingHistoryRoute =
  protectedDashboardBillingHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => protectedDashboardBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/dashboard': typeof protectedDashboardRouteWithChildren
  '/dashboard/api-keys': typeof protectedDashboardApiKeysRoute
  '/dashboard/billing': typeof protectedDashboardBillingRouteWithChildren
  '/dashboard/invoices': typeof protectedDashboardInvoicesRouteWithChildren
  '/dashboard/profile': typeof protectedDashboardProfileRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteWithChildren
  '/dashboard/billing/history': typeof protectedDashboardBillingHistoryRoute
  '/dashboard/billing/upgrade': typeof protectedDashboardBillingUpgradeRoute
  '/dashboard/invoices/$id': typeof protectedDashboardInvoicesIdRoute
  '/dashboard/settings/company': typeof protectedDashboardSettingsCompanyRoute
  '/dashboard/settings/notifications': typeof protectedDashboardSettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/dashboard': typeof protectedDashboardRouteWithChildren
  '/dashboard/api-keys': typeof protectedDashboardApiKeysRoute
  '/dashboard/billing': typeof protectedDashboardBillingRouteWithChildren
  '/dashboard/invoices': typeof protectedDashboardInvoicesRouteWithChildren
  '/dashboard/profile': typeof protectedDashboardProfileRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteWithChildren
  '/dashboard/billing/history': typeof protectedDashboardBillingHistoryRoute
  '/dashboard/billing/upgrade': typeof protectedDashboardBillingUpgradeRoute
  '/dashboard/invoices/$id': typeof protectedDashboardInvoicesIdRoute
  '/dashboard/settings/company': typeof protectedDashboardSettingsCompanyRoute
  '/dashboard/settings/notifications': typeof protectedDashboardSettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(protected)/dashboard': typeof protectedDashboardRouteWithChildren
  '/(protected)/dashboard/api-keys': typeof protectedDashboardApiKeysRoute
  '/(protected)/dashboard/billing': typeof protectedDashboardBillingRouteWithChildren
  '/(protected)/dashboard/invoices': typeof protectedDashboardInvoicesRouteWithChildren
  '/(protected)/dashboard/profile': typeof protectedDashboardProfileRoute
  '/(protected)/dashboard/settings': typeof protectedDashboardSettingsRouteWithChildren
  '/(protected)/dashboard/billing/history': typeof protectedDashboardBillingHistoryRoute
  '/(protected)/dashboard/billing/upgrade': typeof protectedDashboardBillingUpgradeRoute
  '/(protected)/dashboard/invoices/$id': typeof protectedDashboardInvoicesIdRoute
  '/(protected)/dashboard/settings/company': typeof protectedDashboardSettingsCompanyRoute
  '/(protected)/dashboard/settings/notifications': typeof protectedDashboardSettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/invoices'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/billing/history'
    | '/dashboard/billing/upgrade'
    | '/dashboard/invoices/$id'
    | '/dashboard/settings/company'
    | '/dashboard/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/invoices'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/billing/history'
    | '/dashboard/billing/upgrade'
    | '/dashboard/invoices/$id'
    | '/dashboard/settings/company'
    | '/dashboard/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/(protected)/dashboard'
    | '/(protected)/dashboard/api-keys'
    | '/(protected)/dashboard/billing'
    | '/(protected)/dashboard/invoices'
    | '/(protected)/dashboard/profile'
    | '/(protected)/dashboard/settings'
    | '/(protected)/dashboard/billing/history'
    | '/(protected)/dashboard/billing/upgrade'
    | '/(protected)/dashboard/invoices/$id'
    | '/(protected)/dashboard/settings/company'
    | '/(protected)/dashboard/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/dashboard/settings': {
      id: '/(protected)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof protectedDashboardSettingsRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/profile': {
      id: '/(protected)/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof protectedDashboardProfileRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/invoices': {
      id: '/(protected)/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof protectedDashboardInvoicesRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/billing': {
      id: '/(protected)/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof protectedDashboardBillingRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/api-keys': {
      id: '/(protected)/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof protectedDashboardApiKeysRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/settings/notifications': {
      id: '/(protected)/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof protectedDashboardSettingsNotificationsRouteImport
      parentRoute: typeof protectedDashboardSettingsRoute
    }
    '/(protected)/dashboard/settings/company': {
      id: '/(protected)/dashboard/settings/company'
      path: '/company'
      fullPath: '/dashboard/settings/company'
      preLoaderRoute: typeof protectedDashboardSettingsCompanyRouteImport
      parentRoute: typeof protectedDashboardSettingsRoute
    }
    '/(protected)/dashboard/invoices/$id': {
      id: '/(protected)/dashboard/invoices/$id'
      path: '/$id'
      fullPath: '/dashboard/invoices/$id'
      preLoaderRoute: typeof protectedDashboardInvoicesIdRouteImport
      parentRoute: typeof protectedDashboardInvoicesRoute
    }
    '/(protected)/dashboard/billing/upgrade': {
      id: '/(protected)/dashboard/billing/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/billing/upgrade'
      preLoaderRoute: typeof protectedDashboardBillingUpgradeRouteImport
      parentRoute: typeof protectedDashboardBillingRoute
    }
    '/(protected)/dashboard/billing/history': {
      id: '/(protected)/dashboard/billing/history'
      path: '/history'
      fullPath: '/dashboard/billing/history'
      preLoaderRoute: typeof protectedDashboardBillingHistoryRouteImport
      parentRoute: typeof protectedDashboardBillingRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedDashboardBillingRouteChildren {
  protectedDashboardBillingHistoryRoute: typeof protectedDashboardBillingHistoryRoute
  protectedDashboardBillingUpgradeRoute: typeof protectedDashboardBillingUpgradeRoute
}

const protectedDashboardBillingRouteChildren: protectedDashboardBillingRouteChildren =
  {
    protectedDashboardBillingHistoryRoute:
      protectedDashboardBillingHistoryRoute,
    protectedDashboardBillingUpgradeRoute:
      protectedDashboardBillingUpgradeRoute,
  }

const protectedDashboardBillingRouteWithChildren =
  protectedDashboardBillingRoute._addFileChildren(
    protectedDashboardBillingRouteChildren,
  )

interface protectedDashboardInvoicesRouteChildren {
  protectedDashboardInvoicesIdRoute: typeof protectedDashboardInvoicesIdRoute
}

const protectedDashboardInvoicesRouteChildren: protectedDashboardInvoicesRouteChildren =
  {
    protectedDashboardInvoicesIdRoute: protectedDashboardInvoicesIdRoute,
  }

const protectedDashboardInvoicesRouteWithChildren =
  protectedDashboardInvoicesRoute._addFileChildren(
    protectedDashboardInvoicesRouteChildren,
  )

interface protectedDashboardSettingsRouteChildren {
  protectedDashboardSettingsCompanyRoute: typeof protectedDashboardSettingsCompanyRoute
  protectedDashboardSettingsNotificationsRoute: typeof protectedDashboardSettingsNotificationsRoute
}

const protectedDashboardSettingsRouteChildren: protectedDashboardSettingsRouteChildren =
  {
    protectedDashboardSettingsCompanyRoute:
      protectedDashboardSettingsCompanyRoute,
    protectedDashboardSettingsNotificationsRoute:
      protectedDashboardSettingsNotificationsRoute,
  }

const protectedDashboardSettingsRouteWithChildren =
  protectedDashboardSettingsRoute._addFileChildren(
    protectedDashboardSettingsRouteChildren,
  )

interface protectedDashboardRouteChildren {
  protectedDashboardApiKeysRoute: typeof protectedDashboardApiKeysRoute
  protectedDashboardBillingRoute: typeof protectedDashboardBillingRouteWithChildren
  protectedDashboardInvoicesRoute: typeof protectedDashboardInvoicesRouteWithChildren
  protectedDashboardProfileRoute: typeof protectedDashboardProfileRoute
  protectedDashboardSettingsRoute: typeof protectedDashboardSettingsRouteWithChildren
}

const protectedDashboardRouteChildren: protectedDashboardRouteChildren = {
  protectedDashboardApiKeysRoute: protectedDashboardApiKeysRoute,
  protectedDashboardBillingRoute: protectedDashboardBillingRouteWithChildren,
  protectedDashboardInvoicesRoute: protectedDashboardInvoicesRouteWithChildren,
  protectedDashboardProfileRoute: protectedDashboardProfileRoute,
  protectedDashboardSettingsRoute: protectedDashboardSettingsRouteWithChildren,
}

const protectedDashboardRouteWithChildren =
  protectedDashboardRoute._addFileChildren(protectedDashboardRouteChildren)

interface protectedRouteRouteChildren {
  protectedDashboardRoute: typeof protectedDashboardRouteWithChildren
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardRoute: protectedDashboardRouteWithChildren,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
