/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedDashboardAdminRouteImport } from './routes/(protected)/dashboard/admin'
import { Route as protectedDashboardApiKeysRouteImport } from './routes/(protected)/dashboard/api-keys'
import { Route as protectedDashboardBillingRouteImport } from './routes/(protected)/dashboard/billing'
import { Route as protectedDashboardInvoicesRouteImport } from './routes/(protected)/dashboard/invoices'
import { Route as protectedDashboardReferralsRouteImport } from './routes/(protected)/dashboard/referrals'
import { Route as protectedDashboardSettingsRouteImport } from './routes/(protected)/dashboard/settings'
import { Route as protectedDashboardAdminIndexRouteImport } from './routes/(protected)/dashboard/admin/index'
import { Route as protectedDashboardAdminActivityRouteImport } from './routes/(protected)/dashboard/admin/activity'
import { Route as protectedDashboardAdminUsersRouteImport } from './routes/(protected)/dashboard/admin/users'
import { Route as protectedDashboardBillingIndexRouteImport } from './routes/(protected)/dashboard/billing/index'
import { Route as protectedDashboardBillingHistoryRouteImport } from './routes/(protected)/dashboard/billing/history'
import { Route as protectedDashboardBillingUpgradeRouteImport } from './routes/(protected)/dashboard/billing/upgrade'
import { Route as protectedDashboardInvoicesIndexRouteImport } from './routes/(protected)/dashboard/invoices/index'
import { Route as protectedDashboardInvoicesIdRouteImport } from './routes/(protected)/dashboard/invoices/$id'
import { Route as protectedDashboardSettingsIndexRouteImport } from './routes/(protected)/dashboard/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedDashboardRoute,
} as any)
const protectedDashboardAdminRoute = protectedDashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => protectedDashboardRoute,
} as any)
const protectedDashboardApiKeysRoute =
  protectedDashboardApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardBillingRoute =
  protectedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardInvoicesRoute =
  protectedDashboardInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardReferralsRoute =
  protectedDashboardReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardSettingsRoute =
  protectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => protectedDashboardRoute,
  } as any)
const protectedDashboardAdminIndexRoute =
  protectedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardAdminRoute,
  } as any)
const protectedDashboardAdminActivityRoute =
  protectedDashboardAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => protectedDashboardAdminRoute,
  } as any)
const protectedDashboardAdminUsersRoute =
  protectedDashboardAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => protectedDashboardAdminRoute,
  } as any)
const protectedDashboardBillingIndexRoute =
  protectedDashboardBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardBillingRoute,
  } as any)
const protectedDashboardBillingHistoryRoute =
  protectedDashboardBillingHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => protectedDashboardBillingRoute,
  } as any)
const protectedDashboardBillingUpgradeRoute =
  protectedDashboardBillingUpgradeRouteImport.update({
    id: '/upgrade',
    path: '/upgrade',
    getParentRoute: () => protectedDashboardBillingRoute,
  } as any)
const protectedDashboardInvoicesIndexRoute =
  protectedDashboardInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardInvoicesRoute,
  } as any)
const protectedDashboardInvoicesIdRoute =
  protectedDashboardInvoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => protectedDashboardInvoicesRoute,
  } as any)
const protectedDashboardSettingsIndexRoute =
  protectedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedDashboardSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/dashboard': typeof protectedDashboardRouteWithChildren
  '/dashboard/admin': typeof protectedDashboardAdminRouteWithChildren
  '/dashboard/api-keys': typeof protectedDashboardApiKeysRoute
  '/dashboard/billing': typeof protectedDashboardBillingRouteWithChildren
  '/dashboard/invoices': typeof protectedDashboardInvoicesRouteWithChildren
  '/dashboard/referrals': typeof protectedDashboardReferralsRoute
  '/dashboard/settings': typeof protectedDashboardSettingsRouteWithChildren
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/dashboard/admin/activity': typeof protectedDashboardAdminActivityRoute
  '/dashboard/admin/users': typeof protectedDashboardAdminUsersRoute
  '/dashboard/billing/history': typeof protectedDashboardBillingHistoryRoute
  '/dashboard/billing/upgrade': typeof protectedDashboardBillingUpgradeRoute
  '/dashboard/invoices/$id': typeof protectedDashboardInvoicesIdRoute
  '/dashboard/admin/': typeof protectedDashboardAdminIndexRoute
  '/dashboard/billing/': typeof protectedDashboardBillingIndexRoute
  '/dashboard/invoices/': typeof protectedDashboardInvoicesIndexRoute
  '/dashboard/settings/': typeof protectedDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/dashboard/api-keys': typeof protectedDashboardApiKeysRoute
  '/dashboard/referrals': typeof protectedDashboardReferralsRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/dashboard/admin/activity': typeof protectedDashboardAdminActivityRoute
  '/dashboard/admin/users': typeof protectedDashboardAdminUsersRoute
  '/dashboard/billing/history': typeof protectedDashboardBillingHistoryRoute
  '/dashboard/billing/upgrade': typeof protectedDashboardBillingUpgradeRoute
  '/dashboard/invoices/$id': typeof protectedDashboardInvoicesIdRoute
  '/dashboard/admin': typeof protectedDashboardAdminIndexRoute
  '/dashboard/billing': typeof protectedDashboardBillingIndexRoute
  '/dashboard/invoices': typeof protectedDashboardInvoicesIndexRoute
  '/dashboard/settings': typeof protectedDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(protected)/dashboard': typeof protectedDashboardRouteWithChildren
  '/(protected)/dashboard/admin': typeof protectedDashboardAdminRouteWithChildren
  '/(protected)/dashboard/api-keys': typeof protectedDashboardApiKeysRoute
  '/(protected)/dashboard/billing': typeof protectedDashboardBillingRouteWithChildren
  '/(protected)/dashboard/invoices': typeof protectedDashboardInvoicesRouteWithChildren
  '/(protected)/dashboard/referrals': typeof protectedDashboardReferralsRoute
  '/(protected)/dashboard/settings': typeof protectedDashboardSettingsRouteWithChildren
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/dashboard/admin/activity': typeof protectedDashboardAdminActivityRoute
  '/(protected)/dashboard/admin/users': typeof protectedDashboardAdminUsersRoute
  '/(protected)/dashboard/billing/history': typeof protectedDashboardBillingHistoryRoute
  '/(protected)/dashboard/billing/upgrade': typeof protectedDashboardBillingUpgradeRoute
  '/(protected)/dashboard/invoices/$id': typeof protectedDashboardInvoicesIdRoute
  '/(protected)/dashboard/admin/': typeof protectedDashboardAdminIndexRoute
  '/(protected)/dashboard/billing/': typeof protectedDashboardBillingIndexRoute
  '/(protected)/dashboard/invoices/': typeof protectedDashboardInvoicesIndexRoute
  '/(protected)/dashboard/settings/': typeof protectedDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/invoices'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/activity'
    | '/dashboard/admin/users'
    | '/dashboard/billing/history'
    | '/dashboard/billing/upgrade'
    | '/dashboard/invoices/$id'
    | '/dashboard/admin/'
    | '/dashboard/billing/'
    | '/dashboard/invoices/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard/api-keys'
    | '/dashboard/referrals'
    | '/dashboard'
    | '/dashboard/admin/activity'
    | '/dashboard/admin/users'
    | '/dashboard/billing/history'
    | '/dashboard/billing/upgrade'
    | '/dashboard/invoices/$id'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/invoices'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/(protected)/dashboard'
    | '/(protected)/dashboard/admin'
    | '/(protected)/dashboard/api-keys'
    | '/(protected)/dashboard/billing'
    | '/(protected)/dashboard/invoices'
    | '/(protected)/dashboard/referrals'
    | '/(protected)/dashboard/settings'
    | '/(protected)/dashboard/'
    | '/(protected)/dashboard/admin/activity'
    | '/(protected)/dashboard/admin/users'
    | '/(protected)/dashboard/billing/history'
    | '/(protected)/dashboard/billing/upgrade'
    | '/(protected)/dashboard/invoices/$id'
    | '/(protected)/dashboard/admin/'
    | '/(protected)/dashboard/billing/'
    | '/(protected)/dashboard/invoices/'
    | '/(protected)/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/admin': {
      id: '/(protected)/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof protectedDashboardAdminRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/api-keys': {
      id: '/(protected)/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof protectedDashboardApiKeysRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/billing': {
      id: '/(protected)/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof protectedDashboardBillingRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/invoices': {
      id: '/(protected)/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof protectedDashboardInvoicesRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/referrals': {
      id: '/(protected)/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof protectedDashboardReferralsRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/settings': {
      id: '/(protected)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof protectedDashboardSettingsRouteImport
      parentRoute: typeof protectedDashboardRoute
    }
    '/(protected)/dashboard/admin/': {
      id: '/(protected)/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof protectedDashboardAdminIndexRouteImport
      parentRoute: typeof protectedDashboardAdminRoute
    }
    '/(protected)/dashboard/admin/activity': {
      id: '/(protected)/dashboard/admin/activity'
      path: '/activity'
      fullPath: '/dashboard/admin/activity'
      preLoaderRoute: typeof protectedDashboardAdminActivityRouteImport
      parentRoute: typeof protectedDashboardAdminRoute
    }
    '/(protected)/dashboard/admin/users': {
      id: '/(protected)/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof protectedDashboardAdminUsersRouteImport
      parentRoute: typeof protectedDashboardAdminRoute
    }
    '/(protected)/dashboard/billing/': {
      id: '/(protected)/dashboard/billing/'
      path: '/'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof protectedDashboardBillingIndexRouteImport
      parentRoute: typeof protectedDashboardBillingRoute
    }
    '/(protected)/dashboard/billing/history': {
      id: '/(protected)/dashboard/billing/history'
      path: '/history'
      fullPath: '/dashboard/billing/history'
      preLoaderRoute: typeof protectedDashboardBillingHistoryRouteImport
      parentRoute: typeof protectedDashboardBillingRoute
    }
    '/(protected)/dashboard/billing/upgrade': {
      id: '/(protected)/dashboard/billing/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/billing/upgrade'
      preLoaderRoute: typeof protectedDashboardBillingUpgradeRouteImport
      parentRoute: typeof protectedDashboardBillingRoute
    }
    '/(protected)/dashboard/invoices/': {
      id: '/(protected)/dashboard/invoices/'
      path: '/'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof protectedDashboardInvoicesIndexRouteImport
      parentRoute: typeof protectedDashboardInvoicesRoute
    }
    '/(protected)/dashboard/invoices/$id': {
      id: '/(protected)/dashboard/invoices/$id'
      path: '/$id'
      fullPath: '/dashboard/invoices/$id'
      preLoaderRoute: typeof protectedDashboardInvoicesIdRouteImport
      parentRoute: typeof protectedDashboardInvoicesRoute
    }
    '/(protected)/dashboard/settings/': {
      id: '/(protected)/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof protectedDashboardSettingsIndexRouteImport
      parentRoute: typeof protectedDashboardSettingsRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedDashboardAdminRouteChildren {
  protectedDashboardAdminActivityRoute: typeof protectedDashboardAdminActivityRoute
  protectedDashboardAdminUsersRoute: typeof protectedDashboardAdminUsersRoute
  protectedDashboardAdminIndexRoute: typeof protectedDashboardAdminIndexRoute
}

const protectedDashboardAdminRouteChildren: protectedDashboardAdminRouteChildren =
  {
    protectedDashboardAdminActivityRoute: protectedDashboardAdminActivityRoute,
    protectedDashboardAdminUsersRoute: protectedDashboardAdminUsersRoute,
    protectedDashboardAdminIndexRoute: protectedDashboardAdminIndexRoute,
  }

const protectedDashboardAdminRouteWithChildren =
  protectedDashboardAdminRoute._addFileChildren(
    protectedDashboardAdminRouteChildren,
  )

interface protectedDashboardBillingRouteChildren {
  protectedDashboardBillingHistoryRoute: typeof protectedDashboardBillingHistoryRoute
  protectedDashboardBillingUpgradeRoute: typeof protectedDashboardBillingUpgradeRoute
  protectedDashboardBillingIndexRoute: typeof protectedDashboardBillingIndexRoute
}

const protectedDashboardBillingRouteChildren: protectedDashboardBillingRouteChildren =
  {
    protectedDashboardBillingHistoryRoute:
      protectedDashboardBillingHistoryRoute,
    protectedDashboardBillingUpgradeRoute:
      protectedDashboardBillingUpgradeRoute,
    protectedDashboardBillingIndexRoute: protectedDashboardBillingIndexRoute,
  }

const protectedDashboardBillingRouteWithChildren =
  protectedDashboardBillingRoute._addFileChildren(
    protectedDashboardBillingRouteChildren,
  )

interface protectedDashboardInvoicesRouteChildren {
  protectedDashboardInvoicesIdRoute: typeof protectedDashboardInvoicesIdRoute
  protectedDashboardInvoicesIndexRoute: typeof protectedDashboardInvoicesIndexRoute
}

const protectedDashboardInvoicesRouteChildren: protectedDashboardInvoicesRouteChildren =
  {
    protectedDashboardInvoicesIdRoute: protectedDashboardInvoicesIdRoute,
    protectedDashboardInvoicesIndexRoute: protectedDashboardInvoicesIndexRoute,
  }

const protectedDashboardInvoicesRouteWithChildren =
  protectedDashboardInvoicesRoute._addFileChildren(
    protectedDashboardInvoicesRouteChildren,
  )

interface protectedDashboardSettingsRouteChildren {
  protectedDashboardSettingsIndexRoute: typeof protectedDashboardSettingsIndexRoute
}

const protectedDashboardSettingsRouteChildren: protectedDashboardSettingsRouteChildren =
  {
    protectedDashboardSettingsIndexRoute: protectedDashboardSettingsIndexRoute,
  }

const protectedDashboardSettingsRouteWithChildren =
  protectedDashboardSettingsRoute._addFileChildren(
    protectedDashboardSettingsRouteChildren,
  )

interface protectedDashboardRouteChildren {
  protectedDashboardAdminRoute: typeof protectedDashboardAdminRouteWithChildren
  protectedDashboardApiKeysRoute: typeof protectedDashboardApiKeysRoute
  protectedDashboardBillingRoute: typeof protectedDashboardBillingRouteWithChildren
  protectedDashboardInvoicesRoute: typeof protectedDashboardInvoicesRouteWithChildren
  protectedDashboardReferralsRoute: typeof protectedDashboardReferralsRoute
  protectedDashboardSettingsRoute: typeof protectedDashboardSettingsRouteWithChildren
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
}

const protectedDashboardRouteChildren: protectedDashboardRouteChildren = {
  protectedDashboardAdminRoute: protectedDashboardAdminRouteWithChildren,
  protectedDashboardApiKeysRoute: protectedDashboardApiKeysRoute,
  protectedDashboardBillingRoute: protectedDashboardBillingRouteWithChildren,
  protectedDashboardInvoicesRoute: protectedDashboardInvoicesRouteWithChildren,
  protectedDashboardReferralsRoute: protectedDashboardReferralsRoute,
  protectedDashboardSettingsRoute: protectedDashboardSettingsRouteWithChildren,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
}

const protectedDashboardRouteWithChildren =
  protectedDashboardRoute._addFileChildren(protectedDashboardRouteChildren)

interface protectedRouteRouteChildren {
  protectedDashboardRoute: typeof protectedDashboardRouteWithChildren
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardRoute: protectedDashboardRouteWithChildren,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
